# version: '3.8'
# services:
#   telegram-bot:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
#     # container_name: neurobikesbot
#     # volumes:
#     #   - .:/app
#     # working_dir: /app
#     # command: npm run dev
#     # ports:
#     # - "8080:3000"
#     # - "80:80"
#     # - "8443:8443"
version: '3.8'

services:
  bot:
    image: node:22-alpine  # Используем образ Node.js 16
    container_name: telegram_bot
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app  # Монтируем текущую директорию в /app внутри контейнера
      # - ./node_modules:/app/node_modules
    # ports:
    #   - "3000:3000"  # Порт для отладки (если нужно)
    environment:
      - NODE_ENV=development
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}  # Замените на ваш токен
    command: sh -c "npm install && npm run dev"  # Устанавливаем зависимости и запускаем nodemon
    # command: sh -c "npm run dev"  #запускаем nodemon