version: '3.8'
services:
  app:
    build: ./app
    container_name: neurobikesbot
    image: node:22-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    # ports:
    # - "8080:3000"
    # - "80:80"
    # - "8443:8443"
